### ISSUE TITLE
New api field

### ISSUE THREAD

**Issue by Dartanjan** [lyal/checkr#13]
Hey @lyal I'm getting 
```
Unknown attribute on resource Lyal\Checkr\Entities\Resources\Report: municipal_criminal_search_ids {"exception":"[object] (Lyal\\Checkr\\Exceptions\\InvalidAttributeException(code: 0): Unknown attribute on resource Lyal\\Chec
kr\\Entities\\Resources\\Report: municipal_criminal_search_ids at [...]
```

Looks like `municipal_criminal_search_ids` is needed as well? I just tested and it works once I add it to `Resources/Report.php`.

Not sure if Checkr keeps silently adding those fields or what. Are there any side effects if I just catch `InvalidAttributeException` and ignore it?

Thanks!

**Comment by lyal** [comment]
Sorry for the delay!  You can safely ignore the exception; I could probably stop rigidly enforcing their defined API standard (it's fluid, and doesn't get updated via the docs)

**Comment by pgerov** [comment]
@lyal Probably stopping enforcing the respective fields as they have another new field returned and generating an additional error: `Unknown attribute on resource Lyal/Checkr/Entities/Resources/Report: pointer_state_criminal_search_ids`

**Comment by Dartanjan** [comment]
I think this problem is causing some issues for me. Here's what I'm doing, maybe you can help:

I'm creating a report on a Candidate and returning the resulting Report.

```php
/**
     * @param $candidateId
     *
     * @return mixed
     */
    public function createReport($candidateId)
    {
        try {
            return Checkr::report([
                'package' => 'package_name',
                'candidate_id' => $candidateId
            ])->create();
        } catch (ResourceNotCreated $e) {
            abort(500, sprintf("Checkr report could not be ordered for this candidate: %s. 
            Checkr error: %s", $candidateId, $e->getMessage()));
        } catch (InvalidAttributeException $e) {}

        return null;
    }
```
But what seems to happen is that Checkr creates the report, and then when it tries to parse the results, it throws the error because the field doesn't exist. Which means I'm unable to return the Report object in any way. Even if I do a lookup manually, it will probably throw the same exception when it tries to parse the result from Checkr.

So how do I get a Report object back in order to update user details? Thanks @lyal

**Comment by pgerov** [comment]
@Dartanjan I am doing the following workaround for now to set the new missing fields before calling the `create()` method. This includes the new fields `municipal_criminal_search_ids` and `pointer_state_criminal_search_ids` returned by Checkr.

``` php     
$report = Checkr::report([
   'package' => 'package_name',
   'candidate_id' => $candidateId
]);

$report->setFields([
   'id',
   'object',
   'uri',
   'status',
   'source',
   'created_at',
   'completed_at',
   'upgraded_at',
   'revised_at',
   'tags',
   'turnaround_time',
   'assessment',
   'due_time',
   'adjudication',
   'package',
   'tags',
   'candidate_id',
   'program_id',
   'ssn_trace_id',
   'sex_offender_search_id',
   'federal_criminal_search_id',
   'national_criminal_search_id',
   'global_watchlist_search_id',
   'municipal_criminal_search_ids',
   'pointer_state_criminal_search_ids',
   'county_criminal_search_ids',
   'personal_reference_verification_ids',
   'professional_reference_verification_ids',
   'motor_vehicle_report_id',
   'state_criminal_search_ids',
   'terrorist_watchlist_search_id',
   'facis_search_id',
   'document_ids',
   'geo_ids',
   'tags',
   'arrest_search_id',
   'self_disclosure_ids',
]);
```

**Comment by Dartanjan** [comment]
Thanks @pgerov. I guess you could also just add the missing fields in the second call, as the constructor already calls all the other fields?

`/src/Entities/Resources/Report.php`

```php
/**
     * Report constructor.
     *
     * @param null|string|array $values
     * @param null|Client       $client
     */
    public function __construct($values = null, Client $client = null)
    {
        $this->setFields([
            'id',
            'object',
            'uri',
            'status',
            'source',
...
```

Will try this. Thanks again.

**Comment by pgerov** [comment]
@Dartanjan You are right, you can first get the already set fields using `getFields()` and then reset them.

**Comment by Dartanjan** [comment]
Here's what I ended up doing:

```php
$report = Checkr::report([
    'package' => 'package_name',
    'candidate_id' => $candidateId
]);

$report->setFields(array_merge($report->getFields(), [
    'municipal_criminal_search_ids',
    'pointer_state_criminal_search_ids'
]));

return $report->create();
```

But it would still be best if exceptions are not thrown for unknown fields.
