### ISSUE TITLE
Use keys from config, not env?

### ISSUE THREAD

**Issue by Dartanjan** [lyal/checkr#5]
Hi, thanks for doing this package!

I noticed that keys are fetched from `env` directly. Wouldn't fetching from `config('checkr.key_production')` be more effective as config will be cached and faster to access?

Thanks

**Comment by lyal** [comment]
Good call -- moving from .env to a config call wrapping the .env under the laravel directory. 
 getenv is still used in the generic client though.

For changes, see: https://github.com/lyal/checkr/commit/3c64ad3ca7da45282c53017de9cdce989023f465
