### ISSUE TITLE
Best way to test the integration?

### ISSUE THREAD

**Issue by Dartanjan** [lyal/checkr#6]
Hi, what would be the best way to write tests like whether a listener I have runs the correct report?

I tried mocking `Checkr` facade, but that's not working because `Client` instantiates new Resource classes manually (`new $resource(...)`).

I then tried mocking `Resource` and `Client` like this:
```
$checkrReport = Mockery::mock(Report::class);
        $checkrReport
            ->shouldReceive('create')
            ->once()
            ->andReturn((object) ['id' => 66]);

        $checkrClient = Mockery::mock(Client::class);
        $checkrClient
            ->shouldReceive('api')
            ->once()
            ->with('report', ['package' => 'driver_pro', 'candidate_id' => 1])
            ->andReturn($checkrReport);

$this->app->instance(Client::class, $checkrClient);
```

But that didn't get me past `Lyal\Checkr\Exceptions\Client\NotFound: The requested resource could not be found. Response: {"error":"TestCandidate not found"}`.

Any thoughts?

**Comment by lyal** [comment]
Take a look at the API and Unit tests that are written under Tests.
